language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t murtuza5689/docker-react -f ./frontend/Dockerfile.dev ./

script:
    - docker run -e CI=true murtuza5689/docker-react npm run test